name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh -t -o StrictHostKeyChecking=no valian@0.tcp.ngrok.io -p 17336 << 'EOF'
        cd /home/valian/node-hello
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF
